# Generated by Django 4.2.3 on 2023-07-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='pin_code',
        ),
    ]
